### PR TITLE
Add memory package

### PR DESCRIPTION
**Pull request by belka-ew**
#110

### CODE REVIEW

**Comment by belka-ew** [comment]
It is my suggestion for the Allocator interface and one simple allocator implementation.

**Comment by belka-ew** [comment]
And I will inverstigate time next days in finding out why it fails on everything except dmd 0.71.0 x86_64

**Comment by gecko0307** [comment]
Seems working now. I had to drop support for dmd 2.068 because of pragma(inline), though.

**Comment by belka-ew** [comment]
2.068's TypeInfo seems to miss "initializer" aswell. I got with dmd 2.068.2:

dlib/memory/mmappool.d(307,53): Error: no property 'initializer' for type 'object.TypeInfo_Class'

**Pull request merged**
