### PR TITLE
Crypto package. DES

### PR DESCRIPTION
**Pull request by belka-ew**
- dlib.container.bit : BitVector. ubyte[] wrapper that allows extended access to the array on the bit level (shift operations, iterating through all the bits, bitwise operations).
- dlib.crypto: Generic interfaces for implementing symmetric ciphers and the first version of DES (Data Encryption Standard)
- small fixes for async documentation

### CODE REVIEW

**Comment by belka-ew** [comment]
Looks for me like a weired issue with 2.070.2 (DMD as well). If I remove dlib.crypto.symmetric.SymmetricCipher.key then it passes the tests. Otherwise dlib.crypto.symmetric.DES.key is called twice instead of one time and the second time with the wrong value.
I can remove the @property from the interface till there is only one implementation (the second one will be AES) or execute the tests only if the compiler is 2.071.0 or you can leave the pull request open since there is nothing interesting for now and it need some more algorithms. LDC 1.1.0 is already in beta, maybe the new version will come out soon.
What do you think?

**Comment by minexew** [comment]
I don't want to put your work down in any way, but are you really sure it's wise for Dlib to roll its own crypto? Especially outdated crypto like DES.

In my *opinion* it would be much better to just wrap OpenSSL or one of the well-tested alternatives.

**Comment by belka-ew** [comment]
DES isn't really important here. It is just very simple and I used it to create the generic interfaces for ciphers. My work is all about TLS 1.2 support and it doesn't support DES, but AES, RSA and so on. Your concern is absolutely justified and in the following text I'd like to explain my thoughts behind this package and would be happy about any feedback.

I developed an event loop in dlib.async and should anyway support TLS, because TLS becomes every day more important: There is LetsEncrypt that signs free TLS certificats and no of modern browsers support HTTP2 without HTTPS.
Now cryptography isn't simple and almost all cryptography implementations a separate libraries: crypto++, botan, nss, openssl, libgcrypt and so on. So I fully if understand if  a crypo package maybe isn't suitable for a general purpose library. On the other hand there was a try to create a crypto library for c++ boost: https://svn.boost.org/trac/boost/wiki/LibrariesUnderConstruction, it just wasn't finished. And all libraries I mentioned above are full-blown crypto libraries. I don't care about a full-blown crypto library, I'm interested only in algorithms needed for modern TLS support.

So there are following ways I could imagine to continue the work:
- crypto support in dlib. Since the cryptography requires a lot of testing, it would be better to create something like dlib.experimental.crypto (like phobos) or I could just work in crypto branch and we could see then if this work would get some attention from dlib users or it should be splitted.
- I wouldn't wrap OpenSSL but use a native D implementation. There is botan by etcimon. Botan is also a full-blown crypto library, but I heard it has some problems on Windows. It would mean an optional dependency for dlib on an extern library, that would be still undesirable for dlib's independency.
- My event loop is mostly inspired by libev and python's asyncio. Asyncio depends heavy on OpenSSL and doesn't have an interface to work with another crypto libraries. The same problem has my event loop aswell. But I could investigate some time in developing an interface to support extern TLS libraries. It would give more freedom to the users but they would have to implement the TLS support by themselves.

Everything here is ok for me. I just like dlib for its design and want to support its mission and contribute to it :) And would leave the decision to @gecko0307 and dlib users.

**Comment by gecko0307** [comment]
In principle, I have nothing against crypto package in dlib, but, since I'm not an expert, it's doubtful that I will support it in future. Async stuff is already outside of my competence :) And, considering the important role cryptography plays in security, I don't want it to become a weak side of the library.

**Comment by belka-ew** [comment]
If everything goes as expected, I will permanently work on these packages and of cause I would take care of async and crypto related issues.
My opinion is to give crypto a try. I would suggest to create a "crypto" branch, then it would be visible to the world (a bit better than just a dlib-fork), but at the same time not official. After the work has been finished and API becomes stable we can decide if it can be merged, deleted or splitted into a separate repository.
Any thoughts?

**Comment by gecko0307** [comment]
Yes, a special branch for this would be a good place for a start.

**Comment by gecko0307** [comment]
I've created a crypto branch and merged this pr.

https://github.com/gecko0307/dlib/tree/crypto

**Pull request closed without merging**
