### PR TITLE
Event loop

### PR DESCRIPTION
**Pull request by belka-ew**
I could finish faster than I thought.

I called the package with the event loop "async" since it seems to be the standard name everywhere.

* I added dlib.container.buffer. There one normal buffer and one circular buffer working with ubyte (not templated). They actually useful for C-functions working with void pointers (recv, send, write...) If they are not general enough for containers, I can move them to dlib.async aswell.

* I also added another Allocator: Mallocator and set it to the default one. It works similar to allocate/deallocate from dlib.core.memory. You can look, if it works for another packages in the library.

* I really had a difficult time to design how the default allocator should be choosen. My end solution now is to use a global allocator (defaultAllocator) in dlib.memory.
If it won't be enough and other packages will need their own global allocators, I'm not sure where to put them (package.d or some module). If the allocator should be "package" allocator it belongs to package.d but I had some problems with circular references between modules, if package.d and a module in the package have a constructor. I would be really helpful for any ideas how it can be handled better. Or we can just try it and see what problems will appear and then fix them.
It may be worth considering to pass the allocator to constructors of some generic classes, like containers, since they may be used by different modules and it can be difficult to define something like "container allocator".

### CODE REVIEW

**Comment by gecko0307** [comment]
I think we should start by replacing internals of `dlib.core.memory` by Mallocator, and then eventually redesign all packages to support custom allocators. IMO, there is no easy way to do it in one step, because they all use different memory policies (like image factories in `dlib.image` or static selection in `dlib.math.tensor`).

**Comment by gecko0307** [comment]
Is this event loop Posix-only? Doesn't compile on Windows.

**Comment by belka-ew** [comment]
It is Linux-only for now, it won't work on Windows but it should compile at least. Let me check it in a few hours.

**Comment by belka-ew** [comment]
oh, of cause it doesn't work: the allocator is posix-only. My fault. Can I put the whole loop in "version (Posix)" temporally? I need a GC-free std.socket version and a windows-compatible allocator first to abstract away the platform. And I need some time for this (maybe a week)

**Comment by gecko0307** [comment]
Yes, I could do that myself, just wanted to make sure.

**Pull request merged**
