### PR TITLE
Implementation of region props

### PR DESCRIPTION
**Pull request by aferust**
Regionprops functionality has been started to implement. A faster ellipse fitting code is needed, because current one takes a long time (about 0.1 s). Convexhull method needs some checks for correctness.

### CODE REVIEW

**Comment by gecko0307** [comment]
Merging, but before it can be released, this functionality should be rewritten to use `dlib.core.memory` , GC-free containers and image factories if possible, like other modules in `dlib.image`. I've pointed this out in [guidelines](https://github.com/gecko0307/dlib/blob/master/CONTRIBUTING.md#implementing-new-features). There's also [a wiki page on this topic](https://github.com/gecko0307/dlib/wiki/Best-Practice).

**Comment by aferust** [comment]
Thank you for merging. It would be more comfortable if there was a non-square (rectangular) matrix type with routines such as determinant, multiplication, inverse etc. I am doing my best to understand memory system of dlib, but need some time. An eigen values - vector solver would also simplify many things such as ellipse fitting from second moment matrix. I cannot promise that I will tidy things up in a short time.

**Comment by gecko0307** [comment]
Generic matrix type is planned. I will implement in on top of Tensor type (`dlib.math.tensor`), which itself needs some refactoring first. This just has lower priority, because dlib is targeted mainly to game engine math. 
If this work can't be done quickly, I think it's better to make a branch for it and remove it from master.

**Comment by aferust** [comment]
Ok. I think it is better you revert back my pull request. When it is mature enough I make a pull request again. Revert back, and I make a fork to work on it.

**Pull request merged**
